version: 2

project_name: git-de

before:
  hooks:
    - go mod tidy

builds:
  - id: git-de
    main: ./cmd/git-de
    binary: git-de
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: git-de
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else }}{{ .Arch }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^ci:"
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: "Features"
      regexp: "^feat[(:]"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix[(:]"
      order: 1
    - title: "Other"
      order: 999

release:
  github:
    owner: whatsmynameidontknow
    name: git-de
  footer: |
    ## Installation
    
    ```bash
    go install github.com/whatsmynameidontknow/git-de/cmd/git-de@{{ .Tag }}
    ```
