name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
      - name: Run Windows tests
        run: GOOS=windows GOARCH=amd64 go test -v ./...
      - name: Run Linux tests
        run: GOOS=linux GOARCH=amd64 go test -v ./...
      - run: |
          VERSION=$(git describe --tags)
          VERSION=${VERSION#v}
          go build -v --ldflags "-X main.version=$VERSION" ./cmd/git-de

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
